### ISSUE TITLE
Document charts best practices (from initiative in helm/charts)

### ISSUE THREAD

**Issue by scottrigby** [helm/helm-www#1258]
## Current status

The goal of me moving this issue is to be able to archive the helm/charts repo and make sure that the work started/pinned here makes its way into helm.sh/docs.

Some of this has already made it's way into the docs, but there are other valuable things collaborated on here which have not yet. It's been in the back of my mind for a while but I just haven't spent the time to move it to the docs. It may need another round of review by Charts team maintainers and others once we do, because k8s has moved a lot since then!

### Plan

From the past few Charts dev meetings, we all planned to collaborate on clarifying Charts best practices. There have been no PRs to do that thus far (as we approached and are now recovering from KubeCon), so in Today's meeting I volunteered to sketch up an issue to provide some structure to help us do this asynchronously.

The plan is to start with the lowest hanging fruit first, and iterate from there:

1. Sketch up a simple list - in this issue - pointing to which charts are good examples of items in the running list (this would be a good place to quickly note any caveats or questions we may have about those)
2. Make PR for adding documentation to `REVIEW_GUIDELINES.md` about each item in the running list
3. Once this is done, and announced, we could then iterate on adding some version of these best practices into chartutil's create command

### Domains/Topics

The idea is to break out best practices by domain/topic (or some way of thinking about grouping k8s primitives and concepts as they map to helm/charts implementation). Here's a working list, with names of volunteers so far to work on them:

- [x] PVCs/StorageClass @prydonius (see helm/charts#1869, helm/charts#4223) 
- [x] RBAC @unguiculus (https://github.com/kubernetes/helm/pull/3408) 
    - https://github.com/coreos/alb-ingress-controller/pull/146
    - https://github.com/kubernetes/helm/pull/3184
- [ ] Network policy @omkensey (issue helm/charts#4067 - needs a PR)
- [x] StatefulSets @dhilipkumars helm/charts#3334
- [x] Deployment @dhilipkumars helm/charts#3334 
- [x] Jobs @dhilipkumars  helm/charts#3334
- [x] ReplicaSet @dhilipkumars helm/charts#3334
- [x] DaemonSet @dhilipkumars helm/charts#3334
- [x] HorizontalPodAutoscaler @paulczar helm/charts#7562 (see https://github.com/helm/charts/issues/3011#issuecomment-417043738)
- [x] Ingress @prydonius @scottrigby (#7590)
- [ ] Affinity/Antiaffinity (briefly mentioned in helm/charts#3334)
- [x] ServiceAccount (see https://github.com/kubernetes/helm/issues/3320, https://github.com/kubernetes/helm/pull/3408)
- [ ] PodSecurityPolicy @paulczar 
- [ ] PodDisruptionBudget (briefly mentioned in helm/charts#3334. See https://github.com/helm/charts/issues/3011#issuecomment-419233266)
- [x] Label immutability (See helm/charts#7680, helm/charts#7803, helm/charts#7726) @desaintmartin 
- [ ] Standard keys & terminology
    - Today (12 June 2018) discussed making this a new section in the [Helm best practices conventions document](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/conventions.md), where we can distinguish the semantic meaning of `create` vs `enable` keys, etc.
- [ ] Standard commands
    - When to use `include` and `template` (See https://github.com/helm/charts/issues/3011#issuecomment-457637650, https://github.com/helm/charts/issues/3011#issuecomment-457640417, https://github.com/helm/helm/issues/4092 and https://github.com/helm/helm/pull/4093)
- [x] Versioning @scottrigby (#11207)
- [ ] OWNERS file (We should note what was decided here https://github.com/helm/charts/issues/7446#issuecomment-443466712 in the [REVIEW_GUIDELINES](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md))

### Related issues

- https://github.com/kubernetes/helm/issues/1993
- https://github.com/kubernetes/helm/pull/2007
- https://github.com/kubernetes/charts/issues/44

**Comment by angellk** [comment]
@scottrigby is this something you're still working on? if not, please close :)

**Comment by scottrigby** [comment]
Most of this has made its way into the Helm docs by this point. Closing 😄 If anyone notices something missing, please open a PR in helm/helm-www. Thanks for all the love! ❤️
